version: '3.8'

services:
  web:
    build: ./app
    command: python3 manage.py runserver
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env_vars
    depends_on:
      - db
      
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=

volumes:
  postgres_data:
